
version: '3'
services:
  server:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/fast
      - ./fast/node_modules
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:z2pBe4WhibcXFfRhpSG7@containers-us-west-147.railway.app:6651/railway
      AT_SECRET: at-secret
  