version: '3'
services:
  db:
    image: postgres:alpine3.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres-younes
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nestjs
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "nestjs", "-U", "postgres-younes" ]
      interval: 3s
      timeout: 5s
      retries: 3
  server:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/fast
      - ./fast/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres-younes:123456789@db:5432/nestjs?schema=public
  

